### ISSUE TITLE
is this library maintained?

### ISSUE THREAD

**Issue by Gxmadix** [jazzband/django-payments#211]
Hello, 

the last commit, was Nov 9, 2018, is this library maintained? 

Thanks in advance

**Comment by NyanKiyoshi** [comment]
Hi!

Yes it is 👍

**Comment by WhyNotHugo** [comment]
I'd very much like to use and contribute to this library, but maintenance seems to be quite pause.

I've pushed a PR to unbreak CI, but I'm not getting any feedback: #222.
I reported the breakage about a week before, but also no signs of life.

**Comment by WhyNotHugo** [comment]
Hi! I'm wanting to migrate a few medium-sized sites from a mix of loose integrations into django-payments.

However, it seems that maintenance has slowed down (maybe your no longer actively working on projects that use this?).

I'm wonder if you would be willing to consider giving me maintainer privileges to this repository. As a reference, I've done [a few contributions](https://github.com/mirumee/django-payments/pulls?q=is%3Apr+author%3AWhyNotHugo+is%3Aclosed) so far, as well as some minor ones to [django itself](https://github.com/django/django/pulls?q=is%3Apr+is%3Aclosed+author%3AWhyNotHugo), and multiple [jazzband](https://github.com/jazzband/) projects. You can also check my profile as a reference of other of my works.

Hope this doesn't come of as to pretentious, just wanting to contribute!
Cheers!

**Comment by patrys** [comment]
@WhyNotHugo We're actually considering contributing this project to Jazzband where you could adopt it. The main stopper is the lack of enough documentation for Jazzband to accept it. Would you be willing to help in this area?

**Comment by WhyNotHugo** [comment]
I think the [first step](https://jazzband.co/about/guidelines) is to initiate a GitHub transfer.

I understand this should auto-open an issue in their repositories. Feel free to link here or tag me when that comes up.

Lemme know if you hit any issues. Thanks a lot for pushing this through!
