### ISSUE TITLE
Switch from Travis to GitHub Action

### ISSUE THREAD

**Issue by NyanKiyoshi** [jazzband/django-payments#237]
In my experience from working with Travis a often encountered bottleneck with it is that they are often late when it comes to releasing the newest Python versions, recent example Python 3.9 was in release candidate but the only version available on Travis was an alpha one as well as Python 3.9 [is not yet supported by travis](https://travis-ci.com/github/jazzband/django-payments/jobs/397904654), we still need to use the `-dev` suffix.

I would suggest switching to a GitHub Action so it is easier to test against latest releases without being blocked by the CI provider.

I am suggesting using the action `actions/setup-python@v2` against a [Job Matrix](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix).

When it comes to building against Django master and Python release candidates, we could use [Experimental Jobs](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#example-including-new-combinations).

If the decision is positive about this matter, I am willing to create a workflow and a pull request during this week.

**Comment by jezdez** [comment]
@NyanKiyoshi Hi, I'm the Jazzband founder and roadie (read: admin), and I just wanted to say that it's indeed worth doing this and embrace GitHub actions.

Note, in https://github.com/jazzband/django-payments/commit/0418348c26987ccdfc8dada4d9c1c00b467d1fc2 I added the configuration for the Jazzband release system, which will need to be ported to GitHub actions (there is a PyPI GitHub action from the PyPA folks).

A good example that has worked for another Jazzband project recently is prettytable (cc @hugovk): https://github.com/jazzband/prettytable/blob/master/.github/workflows/deploy.yml

**Comment by jezdez** [comment]
Oops, didn't mean to close this.

**Comment by jezdez** [comment]
Fixed by #246.
