### ISSUE TITLE
pre-commit.ci

### ISSUE THREAD

**Issue by WhyNotHugo** [jazzband/django-payments#259]
I'd like to use [pre-commit.ci](https://pre-commit.ci/) to run linting on CI.  
It's faster and simpler than Actions, and the same service also sends weekly PRs updating and outdated hooks.

@jezdez Is this something you can look at? It's already on for another jazzband project. The only thing needed here is permissions:

https://results.pre-commit.ci/install/github/14595427

**Comment by jezdez** [comment]
Yeah, I've gotten the request and just approved it. Thanks for the patience!
