### ISSUE TITLE
Releasing to GitHub Actions fails

### ISSUE THREAD

**Issue by WhyNotHugo** [jazzband/django-payments#267]
I've pushed a tag, but pushing to GA is failing:

https://github.com/jazzband/django-payments/runs/3624020481

The error is a bit obscure, and I've only found information in the context of a PR, but not in the context of a tag being pushed.

@jezdez Any ideas?

**Comment by WhyNotHugo** [comment]
I've checked and the commit still exists in the referenced repository.

**Comment by WhyNotHugo** [comment]
I think the action runs with the permission of the person that did the push and _I_ don't have permission for it, but I'm not 100% certain. @jezdez Can you retry it and see if that changes anything?

**Comment by jezdez** [comment]
That's curious, https://github.com/actions/first-interaction/issues/10 talks about this a bit, in usually means the user executing the action step doesn't have the correct permissions, which is odd. I'll dig into this why that doesn't work.

**Comment by jezdez** [comment]
@WhyNotHugo I've add a condition to make sure the workflow is only run on "pushing" the tag: https://github.com/jazzband/django-payments/commit/947ca6e672140d52544d0f58f710d56df3aa4216. This was a tip from https://github.com/actions/create-release/issues/103#issuecomment-723415360.

Could you deleted and redo the tag based on the current master please?

**Comment by WhyNotHugo** [comment]
I don't really understand the change TBH.

The [workflow is set to only run for tag push events](https://github.com/jazzband/django-payments/blob/947ca6e672140d52544d0f58f710d56df3aa4216/.github/workflows/release.yml#L3-L6). So this `if` sounds like it should always be true.

Seems to have failed with the same error: https://github.com/jazzband/django-payments/runs/3636459337#step:7:12

I'd say maybe keeping GH Releases isn't worth further hassle, but I'm not sure pushing to PyPI would work either.

**Comment by jezdez** [comment]
> I don't really understand the change TBH.
> 
> The [workflow is set to only run for tag push events](https://github.com/jazzband/django-payments/blob/947ca6e672140d52544d0f58f710d56df3aa4216/.github/workflows/release.yml#L3-L6). So this `if` sounds like it should always be true.
> 
> Seems to have failed with the same error: https://github.com/jazzband/django-payments/runs/3636459337#step:7:12
> 
> I'd say maybe keeping GH Releases isn't worth further hassle, but I'm not sure pushing to PyPI would work either.

Yeah, let's try removing the gh release part and see if the push to the Jazzband index works. I haven't seen any issues with that in other Jazzband project at least. This could be a change in the GitHub API, since I don't see an [obvious change in the action we use](https://github.com/svenstaro/upload-release-action/compare/2.2.1...master).

Can you open a PR for the removal of the GH release action? Or alternatively want to look for a different action we can try?
