### ISSUE TITLE
Please do not release 0.16 - bump major version

### ISSUE THREAD

**Issue by Natureshadow** [jazzband/django-payments#305]
Hi,

the changelog mentions that the introduction of the new `billing_phone` requires making a new migratio nfor downstream projects. This is a breaking change – downstreams relying on semantic versioning can auto-upgrade from 0.15 to 0.16 without expecting the breakage.

Thus, I strongly suggest to bump to 1.0 instead (which wil lalso make semantic versioning start working properly, because strictly speaking, semantic versioning does not exist prior to 1.0). (That said, it is perfectly legal even under semver to introduce breaking changes between 0.15 and 0.16 ;)).

**Comment by WhyNotHugo** [comment]
We've been pushing the minor version for breaking changes so far (due to being 0.x), but you're quite right.

I'll cancel 0.16.0, and bump to 1.0.0. I want to also clarify this a bit in the changelog, so will likely do this at the end of the day.
