### ISSUE TITLE
django-phonenumber-field requirement too strict?

### ISSUE THREAD

**Issue by whyscream** [jazzband/django-payments#338]
Hi,

I'm trying to implement a better payment solution in an existing setup. The customer is using [Oscar ecommerce](https://django-oscar.readthedocs.io/), the latest release has the following pin: `django-phonenumber-field<6.0.0,>=4.0.0`
This conflicts with the pinning of `django-phonenumber-field>=6.0.0` that django-payments uses.

Looking at the code in django-payments, I don't see anything that requires this minimal version: the model field is used and that's about it. The 'support for python3.10' that was added in django-phonenumber-field==6.0.0 are only changes to the test matrix and docs, no actual codechanges have been done. 

Would you consider a more lenient pinning, to f.i. 5.0.0? Happy to submit a PR, of course

FYI I'm trying to implement PSP Mollie using django-payments and Oscar. As being the maintainer of the [Mollie Python SDK](https://github.com/mollie/mollie-api-python/), also interested in releasing it as a general plugin to django-payments, and also supporting multiple payments methods through Mollie in the end (not only iDeal as suggested/requested in some places).

**Comment by whyscream** [comment]
@WhyNotHugo Could we also get a new release out with this change?

**Comment by WhyNotHugo** [comment]
Need to update the changelog and I'll push a release. I'm blocked because I can't merge things into the main branch any more; asked for help in https://github.com/jazzband/help/issues/329
