### ISSUE TITLE
Issue on installation

### ISSUE THREAD

**Issue by mariofix** [jazzband/django-payments#346]
Hello, I was doing some tests with your app and i seem to have missing something.

```
I followed the instructions and get an error when trying to view the details
AttributeError at /payment-details/4
'Payment' object has no attribute 'order'
Request Method:	POST
Django Version:	4.1.8
Exception Type:	AttributeError
Exception Value:	
'Payment' object has no attribute 'order'
Exception Location:	[PATH]/lib/python3.11/site-packages/payments/stripe/forms.py, line 47, in clean
Raised during:	zvn.views.payment_details
Python Executable:	[PATH]/bin/python
Python Version:	3.11.1

```

I also tried to copy/pase the code from the test directory but i get the same issue.

Any help is appreciated

**Comment by WhyNotHugo** [comment]
Can you post the full stacktrace? Is it [this line](https://github.com/jazzband/django-payments/blob/784ba1bcccaf0927c26f5fe564bdc71d177a413f/payments/stripe/forms.py#L47)?

Looks like the stripe provider expects your `Payment` type to have an `order` attribute which has a `get_metadata()` method. This isn't very clean and not documented at all; it should be entirely optional.

**Comment by mariofix** [comment]
Thanks for your reply! Sorry It took a while for mine.

> Can you post the full stacktrace? Is it [this line](https://github.com/jazzband/django-payments/blob/784ba1bcccaf0927c26f5fe564bdc71d177a413f/payments/stripe/forms.py#L47)?
> 
> Looks like the stripe provider expects your `Payment` type to have an `order` attribute which has a `get_metadata()` method. This isn't very clean and not documented at all; it should be entirely optional.

Yes, that's the line, and that's the reason.

**Comment by WhyNotHugo** [comment]
I think the Stripe provider should be updated to take this `order` attribute only conditionally, and fall back to `None`.

Can you test if such a change works for you? I don't think any metadata is mandatory.

**Comment by mariofix** [comment]
Is was a simple enough change https://github.com/mariofix/django-payments/tree/issue-346
