### ISSUE TITLE
Stripe always multiples amount by 100

### ISSUE THREAD

**Issue by WhyNotHugo** [jazzband/django-payments#350]
The stripe provider always multiples total amounts by 100. This works well for currencies where the subunit is 1/100, but will change the wrong amount for other currencies (e.g.: CLP).

I'm not sure how to address this; we should take great care so as not to break existing integrations.

Referenced in: https://github.com/jazzband/django-payments/pull/349

**Comment by mariofix** [comment]
Well, the model has the currency code, and with something like Managed Attributes, or simply checking the currency code to make the conversion -if needed- when the session is created.

I'll add it to my next pull request.

[Stripe Docs](https://stripe.com/docs/currencies )
