### ISSUE TITLE
Enable RTD build previews for PRs

### ISSUE THREAD

**Issue by WhyNotHugo** [jazzband/django-payments#355]
This can help us pick up breakage in RTD before merging.

See: https://docs.readthedocs.io/en/stable/pull-requests.html

This needs to be done by an RTD admin. Currently these are @patrys and @jazzband.

**Comment by jezdez** [comment]
Just enabled them.

**Comment by jezdez** [comment]
Seems to work, as shown in #348.

**Comment by WhyNotHugo** [comment]
Thanks!
