### ISSUE TITLE
Can't make Paypal payment, "You've been inactive for a while..."

### ISSUE THREAD

**Issue by RyanHope** [jazzband/django-payments#372]
![image](https://github.com/jazzband/django-payments/assets/141005/2d94436e-84df-479e-91ed-98fca642ce10)

How do I avoid this? How do I fix this?

**Comment by WhyNotHugo** [comment]
This is unrelated to this project. Contact Paypal.

**Comment by RyanHope** [comment]
Actually, it seems to be related to how I was improperly using the Payment and Invoice instances in my cart implementation, so it was related to this project.

**Comment by RyanHope** [comment]
There is no error logged on the Paypal site. I believe the issue was a stale Payment object, I was getting the message from the OP on the initial redirect to Paypal's site. Never got an option to log-in to paypal, just would immediately get this message. My cart view was using "get_or_create" to fetch the payment object associated with the current invoice. Now I first delete all old incomplete payments attached to the current invoice and then create a new payment object. After this change, the error went away.
