### ISSUE TITLE
Unable to Access Latest Version of django-payments

### ISSUE THREAD

**Issue by Flerraeter** [jazzband/django-payments#373]
Problem:
I encountered an issue while trying to download the latest version of django-payments. According to the changelog, the current version is 2.1.1. However, when I checked both on pip and the GitHub tags page, only version 2.0.0 is available. This is a problem because there's a bug fix in the later versions that I need (see [this pull request](https://github.com/jazzband/django-payments/pull/349)).

Expected Behavior:
I expect to be able to download and use the newest version of django-payments, which is version 2.1.1, as indicated in the changelog.

Additional Information:
I'm also using pip-tools (https://github.com/jazzband/pip-tools), which is unable to find the newest version of django-payments as well.

Additional Request:
It would be greatly appreciated if you could provide the line to obtain the newest version of django-payments from this GitHub repository using pip-tools if it's possible.

**Comment by WhyNotHugo** [comment]
v2.0.0 is the latest stable release. Looks like we messed up the changelog for the upcoming release.

**Comment by ariroffe** [comment]
Thanks for the answer, I was having the same issue. Is there any timeline for the stable release of ^2.1? I'd be interested in using the new StripeV3 provider in production.
