### ISSUE TITLE
Dummy provider does not set captured_amount

### ISSUE THREAD

**Issue by DragoonAethis** [jazzband/django-payments#374]
Most backends set `captured_amount` when a payment is successful (whether using the "authorization and capture" flow or not), but `DummyProvider` does not. This breaks testing code which expects this value to be set correctly when a payment changes its status.

I'm not sure if this is a bug per se, or if you want to explicitly exclude the dummy provider from having this set.

**Comment by WhyNotHugo** [comment]
`DummyProvider` should behave like others and be usable for this sort of tests. This sounds like a bug.

**Comment by DragoonAethis** [comment]
Thank you! :)
