### ISSUE TITLE
Trying to access master database in slave state

### ISSUE THREAD

**Issue by AhmedSalam22** [jazzband/django-payments#395]
I get this error when I try see payment_details view
![Screenshot (428)](https://github.com/jazzband/django-payments/assets/35177448/16c0f191-941d-443c-9e6c-20507af5e2d7)

`<html>
<body>
<html lang="en" style="--rem: 16; --djdt-font-family-primary: &quot;Segoe UI&quot;, system-ui, Roboto, &quot;Helvetica Neue&quot;,
        Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;,
        &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; --djdt-font-family-monospace: ui-monospace, Menlo, Monaco, &quot;Cascadia Mono&quot;,
        &quot;Segoe UI Mono&quot;, &quot;Roboto Mono&quot;, &quot;Oxygen Mono&quot;, &quot;Ubuntu Monospace&quot;,
        &quot;Source Code Pro&quot;, &quot;Fira Mono&quot;, &quot;Droid Sans Mono&quot;, &quot;Courier New&quot;,
        monospace, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;,
        &quot;Noto Color Emoji&quot;;"><body data-new-gr-c-s-check-loaded="14.1147.0" data-gr-ext-installed="" style="padding: 0px; margin: 0px; font: small sans-serif; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);"><div id="summary" style="padding: 10px 20px; margin: 0px; border-bottom: 1px solid rgb(221, 221, 221); background: rgb(255, 255, 204);"><h1 style="padding: 0px; margin: 0px; font-weight: normal;">RuntimeError at /payment/3</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; word-break: break-word; font-family: sans-serif; color: rgb(87, 87, 87);">Trying to access master database in slave state</pre>
Request Method: | GET
-- | --
http://127.0.0.1:8000/payment/3
4.2.7
RuntimeError
Trying to access master database in slave state
C:\Users\admin\wwork\env\lib\site-packages\django_replicated\router.py, line 78, in db_for_write
openbook_payments.views.payment_details
C:\Users\admin\wwork\env\Scripts\python.exe
3.8.0
['C:\\Users\\admin\\wwork\\ok-api',  'c:\\users\\admin\\appdata\\local\\programs\\python\\python38\\python38.zip',  'c:\\users\\admin\\appdata\\local\\programs\\python\\python38\\DLLs',  'c:\\users\\admin\\appdata\\local\\programs\\python\\python38\\lib',  'c:\\users\\admin\\appdata\\local\\programs\\python\\python38',  'C:\\Users\\admin\\wwork\\env',  'C:\\Users\\admin\\wwork\\env\\lib\\site-packages']
Sun, 31 Dec 2023 12:24:51 +0100

</div><div id="explanation" style="padding: 10px 20px; margin: 0px; border-bottom: 1px solid rgb(221, 221, 221); background: rgb(238, 238, 238);"><p style="padding: 0px; margin: 0px;">You’re seeing this error because you have<span> </span><code style="padding: 0px; margin: 0px; font-size: 10.5625px; white-space: pre-wrap; word-break: break-word;">DEBUG = True</code><span> </span>in your Django settings file. Change that to<span> </span><code style="padding: 0px; margin: 0px; font-size: 10.5625px; white-space: pre-wrap; word-break: break-word;">False</code>, and Django will display a standard page generated by the handler for this status code.</p></div><div id="djDebug" class="" dir="ltr" data-sidebar-url="/__debug__/history_sidebar/" data-default-show="true" style="padding: 0px; margin: 0px; border: 0px; color: rgb(0, 0, 0); background: transparent; min-width: 0px; width: auto; outline: 0px; font-size: 12px; line-height: 1.5em; vertical-align: baseline; font-family: var(--djdt-font-family-primary); text-align: left; text-shadow: none; white-space: normal; transition: none 0s ease 0s;"><div class="" id="djDebugToolbarHandle" style="padding: 0px; margin: 0px; min-width: 0px; width: auto; border-width: 1px 1px 0px; border-top-style: solid; border-right-style: solid; border-bottom-style: initial; border-left-style: solid; border-top-color: rgb(17, 17, 17); border-right-color: rgb(17, 17, 17); border-bottom-color: initial; border-left-color: rgb(17, 17, 17); border-image: initial; outline: 0px; font-size: 12px; line-height: 1.5em; color: rgb(0, 0, 0); vertical-align: baseline; background-color: rgb(255, 255, 255); font-family: var(--djdt-font-family-primary); text-align: left; text-shadow: none; white-space: normal; transition: none 0s ease 0s; position: fixed; transform: translateY(-100%) rotate(-90deg); transform-origin: right bottom; top: 0px; right: 0px; z-index: 100000000; opacity: 0.75;"><div title="Show toolbar" id="djShowToolBarButton" style="padding: 0px 5px; margin: 0px; min-width: 0px; width: auto; border-width: 4px 4px 0px; border-style: solid; border-color: rgb(255, 255, 255); border-image: initial; outline: 0px; font-size: 22px; line-height: 1.5em; color: rgb(255, 255, 255); vertical-align: baseline; background: rgb(0, 0, 0); font-family: var(--djdt-font-family-primary); text-align: left; text-shadow: none; white-space: normal; transition: none 0s ease 0s; font-weight: bold; opacity: 0.5;"><span id="djShowToolBarD" style="padding: 0px; margin: 0px; min-width: 0px; width: auto; border: 0px; outline: 0px; font-size: 22px; line-height: 1.5em; color: rgb(204, 255, 153); vertical-align: baseline; background-color: transparent; font-family: var(--djdt-font-family-primary); text-align: left; text-shadow: none; white-space: normal; transition: none 0s ease 0s;">D</span><span id="djShowToolBarJ" style="padding: 0px; margin: 0px; min-width: 0px; width: auto; border: 0px; outline: 0px; font-size: 16px; line-height: 1.5em; color: rgb(204, 255, 153); vertical-align: baseline; background-color: transparent; font-family: var(--djdt-font-family-primary); text-align: left; text-shadow: none; white-space: normal; transition: none 0s ease 0s;">J</span>DT</div></div></div><div class="betternet-wrapper" style="padding: 10px 20px; margin: 0px; border-bottom: 1px solid rgb(221, 221, 221);"><div id="betternet_content_root" class="betternet_content_clean" style="all: initial;"><div class="betternet_content" style="box-sizing: border-box;"></div></div></div></body><grammarly-desktop-integration data-grammarly-shadow-root="true" style="padding: 0px; margin: 0px;"><div aria-label="grammarly-integration" role="group" tabindex="-1" class="grammarly-desktop-integration" data-content="{&quot;mode&quot;:&quot;full&quot;,&quot;isActive&quot;:true,&quot;isUserDisabled&quot;:false}" style="position: absolute; width: 1px; height: 1px; padding: 0px; margin: -1px; overflow: hidden; clip: rect(0px, 0px, 0px, 0px); white-space: nowrap; border: 0px; user-select: none;"></div></grammarly-desktop-integration></html>
</body>
</html>RuntimeError at /payment/3
Trying to access master database in slave state
Request Method:	GET
Request URL:	http://127.0.0.1:8000/payment/3
Django Version:	4.2.7
Exception Type:	RuntimeError
Exception Value:	
Trying to access master database in slave state
Exception Location:	C:\Users\admin\wwork\env\lib\site-packages\django_replicated\router.py, line 78, in db_for_write
Raised during:	openbook_payments.views.payment_details
Python Executable:	C:\Users\admin\wwork\env\Scripts\python.exe
Python Version:	3.8.0
Python Path:	
['C:\\Users\\admin\\wwork\\ok-api',
 'c:\\users\\admin\\appdata\\local\\programs\\python\\python38\\python38.zip',
 'c:\\users\\admin\\appdata\\local\\programs\\python\\python38\\DLLs',
 'c:\\users\\admin\\appdata\\local\\programs\\python\\python38\\lib',
 'c:\\users\\admin\\appdata\\local\\programs\\python\\python38',
 'C:\\Users\\admin\\wwork\\env',
 'C:\\Users\\admin\\wwork\\env\\lib\\site-packages']
Server time:	Sun, 31 Dec 2023 12:24:51 +0100
Traceback [Switch to copy-and-paste view](http://127.0.0.1:8000/payment/3#)
C:\Users\admin\wwork\env\lib\site-packages\django\core\handlers\exception.py, line 42, in inner
                response = await get_response(request) …
Local vars
C:\Users\admin\wwork\env\lib\site-packages\django\core\handlers\base.py, line 253, in _get_response_async
                response = await wrapped_callback( …
Local vars
C:\Users\admin\wwork\ok-api\openbook_payments\views.py, line 13, in payment_details
        form = payment.get_form(data=request.POST or None) …
Local vars
C:\Users\admin\wwork\env\lib\site-packages\payments\models.py, line 143, in get_form
        return provider.get_form(self, data=data) …
Local vars
C:\Users\admin\wwork\env\lib\site-packages\payments\dummy\__init__.py, line 25, in get_form
            payment.change_status(PaymentStatus.INPUT) …
Local vars
C:\Users\admin\wwork\env\lib\site-packages\payments\models.py, line 97, in change_status
        self.save(update_fields=["status", "message"]) …
Local vars
C:\Users\admin\wwork\env\lib\site-packages\payments\models.py, line 128, in save
        return super().save(**kwargs) …
Local vars
C:\Users\admin\wwork\env\lib\site-packages\django\db\models\base.py, line 780, in save
        using = using or router.db_for_write(self.__class__, instance=self) …
Local vars
C:\Users\admin\wwork\env\lib\site-packages\django\db\utils.py, line 227, in _route_db
                    chosen_db = method(model, **hints) …
Local vars
C:\Users\admin\wwork\env\lib\site-packages\django_replicated\router.py, line 78, in db_for_write
            raise RuntimeError('Trying to access master database in slave state') …
Local vars`

**Comment by denisSurkov** [comment]
I guess this exception is related to "django_replicated" package and has nothing to do with "django-payments". 

I suppose you misconfigured "django_replicated" and wrote url for read only database for "db_for_write".
