### ISSUE TITLE
`Payment.refund()` does not refund

### ISSUE THREAD

**Issue by radekholy24** [jazzband/django-payments#401]
Hello,

**Expected behavior**

> If you need to refund a payment, you can do this by calling the `refund()` method on your Payment instance:
>
> ```python
> from payments import get_payment_model
> Payment = get_payment_model()
> payment = Payment.objects.get()
> payment.refund()
> ```
>
> By default, the total amount would be refunded.

-- https://django-payments.readthedocs.io/en/latest/refund.html

**Actual behavior**

```python
>>> from payments import get_payment_model
>>> Payment = get_payment_model()
>>> payment = Payment.objects.get()
>>> payment.refund()
>>> payment.captured_amount
Decimal("2.00")
>>> payment.status
'confirmed'
```

(Neither the `captured_amount` nor the `status` changes after a call to `refund()`)

**Comment by mariofix** [comment]
Related to #399

**Comment by radekholy24** [comment]
Here is my PR to fix the issue: https://github.com/jazzband/django-payments/pull/410
