### ISSUE TITLE
Django 5.0 support

### ISSUE THREAD

**Issue by silentbugs** [jazzband/django-payments#416]
Does django-payments support django 5.0? Are there any known issues?

**Comment by WhyNotHugo** [comment]
I believe there are no known issues with Django 5.0 at this time. We'd need to update `pyproject.toml` and make sure that tests run with dj 5.0.

**Comment by paulocoutinhox** [comment]
Can you add support for it? Thanks.

**Comment by paulocoutinhox** [comment]
Here: https://github.com/jazzband/django-payments/pull/420

**Comment by WhyNotHugo** [comment]
Fixed via https://github.com/jazzband/django-payments/pull/420
