### ISSUE TITLE
Discussions

### ISSUE THREAD

**Issue by mariofix** [jazzband/django-payments#429]
@WhyNotHugo I was wondering if it's possible to enable the Discussions module from GitHub, I believe we can have more flexibility on how to discuss different implementation without the need for an issue, what do you think?

**Comment by WhyNotHugo** [comment]
Issues are generally fine by me. Do you have anything specific in mind which you feels doesn't fit well?

**Comment by harshalkumar-ishi** [comment]
Why the razorpay is not integrated in this package?
I want to integrate the razorpay in my application to create orders and make payments so for this there is django-payments-razorpay package is included in addition providers but it is not maintained also it is few years old so i cant trust the process of this package if i configure it in PAYMENT_VARIANTS.

**Comment by mariofix** [comment]
Hi @harshalkumar-ishi Razorpay is available trough https://github.com/NyanKiyoshi/django-payments-razorpay/

We support some of the global payments platform, local backends are supported through community modules, you can check a list [here](https://django-payments.readthedocs.io/en/latest/backends.html#community-backends)

@WhyNotHugo This is an example of a discussion and not an issue

**Comment by WhyNotHugo** [comment]
@harshalkumar-ishi The razorpay integration hasn't seen any activity in four years. If we merged that into django-payments, it would have becom an abandoned module that nobody is maintaining and slow down on development of everything else.

Personally, I don't have time to maintain integrations which I don't use. This requires staying up to date with their API, documentation, local rules, and a lot of testing. I simply don't have time for this. I can, at most, review contributions made by others for those modules.

I think maintaining providers in separate modules makes them easier to maintain in the long term, but the providers include in this repository predate my involvement in this project, and moving them out would require extra work and effort that's hard to justify at this point.

**Comment by harshalkumar-ishi** [comment]
Okay @WhyNotHugo  i understand.
